name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Golang setup
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: |
          go build

      - name: Test
        run: go test -v -race ./...
