name: Create release from new tag

# this file is a copy of https://github.com/stretchr/testify/blob/master/.github/workflows/release.yml
# this flow will be run only when new tags are pushed that match our pattern
on:
  push:
    tags:
      - "v[0-9]+.[0.9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub release from tag
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true